# Generated by Django 3.1.3 on 2020-11-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='daylight_hours',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='total_precipitation',
            new_name='precipitation',
        ),
    ]
