# Generated by Django 3.1.3 on 2020-11-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201109_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='hours',
            new_name='daylight',
        ),
    ]
